-- ============================================================================
-- Slot Reservations: Oracle Migration
-- ============================================================================

CREATE TABLE slot_reservation (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id          VARCHAR2(255)  NOT NULL,
    service_id           VARCHAR2(255)  NOT NULL,
    staff_member_id      VARCHAR2(255)  NOT NULL,

    start_utc            TIMESTAMP WITH TIME ZONE NOT NULL,
    end_utc              TIMESTAMP WITH TIME ZONE NOT NULL,

    graph_appointment_id VARCHAR2(255),
    state                VARCHAR2(20)   NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT ck_slot_state    CHECK (state IN ('PENDING', 'CONFIRMED', 'RELEASED')),
    CONSTRAINT ck_slot_zeitraum CHECK (end_utc > start_utc)
);

CREATE INDEX ix_slot_pending_abgelaufen
    ON slot_reservation (state, expires_at);

CREATE INDEX ix_slot_graph_termin
    ON slot_reservation (graph_appointment_id);
